name: ollama-webui-stable-diffusion

services:
  stable-diffusion:
    build:
      context: stable-diffusion
      dockerfile: Dockerfile
    container_name: stable-diffusion
    volumes:
      - ./stable-diffusion/models:/home/myuser/stable-diffusion-webui/models
      - ./stable-diffusion/outputs:/home/myuser/stable-diffusion-webui/outputs
      - ./stable-diffusion/extensions:/home/myuser/stable-diffusion-webui/extensions
      - stable-diffusion:/home/myuser/stable-diffusion-webui
    ports:
      - 7860:7860
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
                
  ollama:
    build:
      context: ollama
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - /mnt/hdd/ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    build:
      context: open-webui
      dockerfile: Dockerfile
    container_name: open-webui
    ports:
      - 3000:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - DEFAULT_MODELS=llama3.1:latest
      - OLLAMA_BASE_URL=http://ollama:11434
      - AUTOMATIC1111_BASE_URL=http://stable-diffusion:7860
      #searxng
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE="searxng"
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL="http://100.69.59.48:6060/search?q=<query>"
      - BROWSER_UI_URL=http://host.docker.internal:7788
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "6060:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      - /docker/pipelines:/app/pipelines  # Assuming you have a volume named pipelines
    networks:
      default:
        aliases:
          - host.docker.internal:host-gateway  # Optional network alias
    restart: unless-stopped  # Optional restart policy

  # browser-ui:
  #   build:
  #     context: https://github.com/browser-use/web-ui.git#main
  #     dockerfile: Dockerfile
  #     container_name: browser-ui
  #     ports:
  #       - "7788:7788"
  #     environment:
  #       - GRADIO_SERVER_NAME=0.0.0.0
  #       - BROWSER_USE_MODEL=deepseek
  #     restart: unless-stopped
  #     networks:
  #       default:
  #         aliases:
  #           - host.docker.internal:host-gateway

volumes:
  stable-diffusion:
  open-webui:
